/*
 * SKUValidatorView.java
 */

package skuvalidator;

import java.awt.CardLayout;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;

/**
 * The application's main frame.
 */
public class SKUValidatorView extends FrameView {

    public SKUValidatorView(SingleFrameApplication app) {
        super(app);

        initComponents();

        // connecting action tasks to status bar via TaskMonito
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        mainPanel = new javax.swing.JPanel();
        Panel1 = new javax.swing.JPanel();
        createProfilesButton = new javax.swing.JButton();
        listProfilesButton = new javax.swing.JButton();
        Panel2 = new CreateProfileView(mainPanel);
        Panel3 = new ListProfilesView(mainPanel);
        modifyProfileButton = new javax.swing.JButton();
        deleteProfileButton = new javax.swing.JButton();

        jFrame1.setName("jFrame1"); // NOI18N

        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new java.awt.CardLayout());

        Panel1.setName("Panel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(skuvalidator.SKUValidatorApp.class).getContext().getResourceMap(SKUValidatorView.class);
        createProfilesButton.setText(resourceMap.getString("createProfilesButton.text")); // NOI18N
        createProfilesButton.setName("createProfilesButton"); // NOI18N
        createProfilesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProfilesButtonActionPerformed(evt);
            }
        });

        listProfilesButton.setText(resourceMap.getString("listProfilesButton.text")); // NOI18N
        listProfilesButton.setName("listProfilesButton"); // NOI18N
        listProfilesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listProfilesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listProfilesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createProfilesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(createProfilesButton)
                .addGap(58, 58, 58)
                .addComponent(listProfilesButton)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        mainPanel.add(Panel1, "card2");

        Panel2.setName("Panel2"); // NOI18N
        mainPanel.add(Panel2, "card3");

        Panel3.setName("Panel3"); // NOI18N

        

        mainPanel.add(Panel3, "card4");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setComponent(mainPanel);
    }

    private void createProfilesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProfilesButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cards = (CardLayout)mainPanel.getLayout();
        cards.show(mainPanel, "card3");
    }//GEN-LAST:event_createProfilesButtonActionPerformed

    private void listProfilesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listProfilesButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cards = (CardLayout)mainPanel.getLayout();
        cards.show(mainPanel, "card4");
    }//GEN-LAST:event_listProfilesButtonActionPerformed

    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JButton createProfilesButton;
    private javax.swing.JButton deleteProfileButton;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JButton listProfilesButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton modifyProfileButton;

}
